apiVersion: apps/v1
kind: Deployment

metadata:
  name: genai-service
  namespace: petclinic
  labels:
    app: genai-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: genai-service

  template:
    metadata:
      labels:
        app: genai-service

    spec:
      containers:
        - name: genai-service

          image: 482352877891.dkr.ecr.ap-south-1.amazonaws.com/pc-dev/genai-service:ab9c8488164f1ccd2da048f67cddd816227110bd

          imagePullPolicy: Always

          ports:
            - containerPort: 8084

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: CONFIG_SERVER_URL
              value: http://config-server:8888

            - name: EUREKA_SERVER_URL
              value: http://discovery-server:8761/eureka

            - name: OPENAI_API_KEY
              value: demo

            - name: AZURE_OPENAI_KEY
              value: demo

            - name: AZURE_OPENAI_ENDPOINT
              value: demo

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"

            limits:
              cpu: "1000m"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084

            initialDelaySeconds: 60
            periodSeconds: 15

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084

            initialDelaySeconds: 90
            periodSeconds: 20
