apiVersion: apps/v1
kind: Deployment

metadata:
  name: discovery-server
  namespace: petclinic
  labels:
    app: discovery-server

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discovery-server

  template:
    metadata:
      labels:
        app: discovery-server

    spec:
      containers:
        - name: discovery-server

          image: 482352877891.dkr.ecr.ap-south-1.amazonaws.com/pc-dev/discovery-server:43cd6979b41b66442e4ab000f8cf4ad297c956e8

          imagePullPolicy: Always

          ports:
            - containerPort: 8761

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: CONFIG_SERVER_URL
              value: http://config-server:8888

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761

            initialDelaySeconds: 40
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761

            initialDelaySeconds: 60
            periodSeconds: 15
