apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: petclinic
  labels:
    app: api-gateway

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway

          image: 482352877891.dkr.ecr.ap-south-1.amazonaws.com/pc-dev/api-gateway:330f2bf0ca790f56e168fc9eccd442cd89e72d32

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: CONFIG_SERVER_URL
              value: http://config-server:8888

            - name: EUREKA_SERVER_URL
              value: http://discovery-server:8761/eureka

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"

            limits:
              cpu: "1000m"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 15

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 90
            periodSeconds: 20
