apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-rds-secret
  namespace: petclinic
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: petclinic-rds-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: pc/dev/rds-credentials
        property: username

    - secretKey: password
      remoteRef:
        key: pc/dev/rds-credentials
        property: password

    - secretKey: host
      remoteRef:
        key: pc/dev/rds-credentials
        property: host

    - secretKey: jdbc-url
      remoteRef:
        key: pc/dev/rds-credentials
        property: jdbc-url
