replicaCount: 1

image:
  repository: 482352877891.dkr.ecr.ap-south-1.amazonaws.com/pc-dev/customers-service
  tag: 9951ed9fcd947ef160195f6feda8967804454f84
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

containerPort: 8081

env:
  - name: SPRING_PROFILES_ACTIVE
    value: kubernetes

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"

  limits:
    memory: "512Mi"
    cpu: "500m"

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 10
