replicaCount: 1

image:
  repository: 482352877891.dkr.ecr.ap-south-1.amazonaws.com/pc-dev/discovery-server
  tag: 5e84cd93058855819696a1c7ace62da6d5a02a67
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8761

containerPort: 8761

env:
  - name: SPRING_PROFILES_ACTIVE
    value: kubernetes

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"

  limits:
    memory: "512Mi"
    cpu: "500m"

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 30
  periodSeconds: 10
