apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - config-server
  - discovery-server

  - customers-service
  - visits-service
  - vets-service

  - api-gateway
  - admin-server
  - genai-service

