apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: petclinic-prod
  namespace: argocd

spec:
  project: petclinic-project

  source:
    repoURL: https://github.com/petclinic-project/petclinic-infrastructure.git
    targetRevision: develop
    path: kubernetes/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
